# Generated by Django 3.0.4 on 2020-03-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_info',
            name='course_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam_info',
            name='num_students',
            field=models.IntegerField(blank=True),
        ),
    ]
