# Generated by Django 3.0.4 on 2020-03-28 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisableDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=0)),
                ('num_students', models.IntegerField(default=0, null=True)),
                ('disable_date', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_first_name', models.CharField(max_length=30)),
                ('instructor_last_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30, null=True)),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('course_number', models.IntegerField(null=True)),
                ('section_number', models.IntegerField(null=True)),
                ('num_students', models.IntegerField(null=True)),
                ('calculator', models.CharField(blank=True, max_length=30)),
                ('notes', models.CharField(blank=True, max_length=30)),
                ('computer_exam', models.BooleanField(default=False)),
                ('scantron', models.BooleanField(default=False)),
                ('timed', models.BooleanField(default=False)),
                ('dictionary', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('test_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.Exam')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('late_start_date', models.DateField(blank=True, null=True)),
                ('late_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
