# Generated by Django 3.0.4 on 2020-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_first_name', models.CharField(blank=True, max_length=30)),
                ('instructor_last_name', models.CharField(blank=True, max_length=30)),
                ('course_name', models.CharField(blank=True, max_length=30)),
                ('course_number', models.IntegerField(blank=True)),
                ('num_students', models.IntegerField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('late_date_start', models.DateField()),
                ('late_date_end', models.DateField()),
                ('timed', models.BooleanField()),
                ('notes', models.BooleanField()),
                ('calculator', models.BooleanField()),
                ('dictionary', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
