# Generated by Django 3.0.4 on 2020-03-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='exam',
            new_name='exam_id',
        ),
    ]
