# Generated by Django 3.0.4 on 2020-03-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200328_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='exam_id',
            field=models.IntegerField(default=0),
        ),
    ]
