# Generated by Django 3.0.4 on 2020-03-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200328_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='test_accepted',
        ),
    ]
