# Generated by Django 3.0.4 on 2020-03-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200307_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('late_start_date', models.DateField(blank=True, null=True)),
                ('late_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='late_end_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='late_start_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
    ]
