# Generated by Django 3.0.6 on 2020-05-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200328_0902'),
        ('main_app', '0004_exam_test_accepted'),
    ]

    operations = [
    ]
