# Generated by Django 3.0.6 on 2020-05-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20200518_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_first_name', models.CharField(max_length=30)),
                ('instructor_last_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30, null=True)),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('course_number', models.IntegerField(null=True)),
                ('section_number', models.IntegerField(null=True)),
                ('num_students', models.IntegerField(null=True)),
                ('calculator', models.CharField(blank=True, max_length=30)),
                ('notes', models.CharField(blank=True, max_length=30)),
                ('computer_exam', models.BooleanField(default=False)),
                ('scantron', models.BooleanField(default=False)),
                ('timed', models.BooleanField(default=False)),
                ('dictionary', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('test_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='date',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='date',
            name='id',
        ),
        migrations.AddField(
            model_name='date',
            name='exam',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.Exam'),
        ),
    ]
